services:
  prod-site:
    image: prod-site:latest
    container_name: prod-site
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      db-network: {}
    ports:
      - 127.0.0.1:8000:8000
    restart: "always"
    secrets:
      - mysql_user_password
    env_file: .env
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password

  certbot:
    image: certbot/dns-cloudflare
    container_name:
      site-certbot
    volumes:
      - certbot_etc:/etc/letsencrypt
      - /root/cloudflare.ini:/root/cloudflare.ini
    networks:
      db-network: {}
    command: >-
      certonly --dns-cloudflare
      --dns-cloudflare-credentials /root/cloudflare.ini
      -m breenc96@gmail.com
      --keep-until-expiring
      --agree-tos --no-eff-email
      -d conorbreen.com


secrets:
  mysql_user_password:
    file: /secrets/mysql_user_password


volumes:
  certbot_etc:


networks:
  db-network:
    external: true
